name: Notificação Discord

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Notificação Discord
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        DISCORD_USERNAME: The Reaper
        DISCORD_AVATAR: https://i.imgur.com/0l33Z8s.png
      uses: Ilshidur/action-discord@master