name: Deploy Bot

on: push

jobs:
  Fast-FTP-Action:
    name: Fast FTP Action
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Fast FTP Action
      uses: anvil-solutions/Fast-FTP-Action@2.1.0
      with:
        server: nbg1.rolledhost.net
        port: 2022
        username: vwlztcz3ibanoqyspb3m.c35f39d5
        password: ${{ secrets.FTP_PASSWORD }}
        method: sftp