name: Deploy Bot

on: push

jobs:
  Fast-FTP-Action:
    name: Fast FTP Action
    runs-on: ubuntu-latest

    steps:
- uses: actions/checkout@v3
- uses: Dylan700/sftp-upload-action@latest
with:
  server: nbg1.rolledhost.net
  username: vwlztcz3ibanoqyspb3m.c35f39d5
  passphrase: ${{secrets.FTP_PASSWORD}}
  port: 2022
  uploads: |
    ./ => ./